import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url))
});

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is generated by Next on every build; linting it is noise.
    ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts']
  },
  {
    rules: {
      // Locale-aware Link lives in @/i18n/navigation; next/link would drop the
      // locale prefix on navigation.
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'next/link',
              message: 'Import { Link } from "@/i18n/navigation" instead.'
            }
          ]
        }
      ]
    }
  }
];

export default config;
